add response code condition

diff --git a/.github/workflows/set-several-private-repos.yaml b/.github/workflows/set-several-private-repos.yaml
--- a/.github/workflows/set-several-private-repos.yaml
+++ b/.github/workflows/set-several-private-repos.yaml
@@ -40,3 +40,9 @@ jobs:
           -H "Accept: application/vnd.github.v3+json" \
           https://api.github.com/repos/$OWNER/$REPO_NAME \
           -d '{"private": true}'
+
+        echo "Response code: $RESPONSE"
+        if [ "$RESPONSE" -ne 200 ]; then
+          echo "Failed to convert $REPO_NAME to private. HTTP status code: $RESPONSE"
+          exit 1
+        fi
